Fix teleport issue and centre the player to the block
horionclient/Horion pull request #121
Opened 2019-10-27 20:01 UTC by montudor

When using the `tp` command, the player will be ~1.5 blocks lower than they chose, causing them to start suffocating (as they fall to the bottom of the second block). This PR fixes that issue and also places the player in the centre of the block they chose to teleport to, just like the official Minecraft command does.

2019-10-27 20:20 UTC, richardletshacks commented
Well it's not 1.5 blocks, it's 1.8 (the player's height).
It'd be better to use `g_Data.getLocalPlayer()->height` here.

2019-10-27 21:01 UTC, montudor commented
Whoops, wondered what the exact value was.

2019-10-29 06:27 UTC, GodGamer029 requested changes

2019-10-29 06:27 UTC, GodGamer029 commented on Horion/Command/Commands/TeleportCommand.cpp
> +	pos.x = assertFloat(args->at(1))+(float)0.5;
You can append an F at the end of the number to declare it a float

2019-11-04 10:22 UTC, GodGamer029 commented
This was added in 3e8c8ae559a4a72bba5be875a4139c168597bd87

2019-11-04 10:22 UTC, closed without merging