Added ChestTP
horionclient/Horion pull request #372
Opened 2020-10-25 11:18 UTC by xXZitRiXx

Tps the Player to chests in a 1 - 100 block radius (can be altered with slider). Probably best to use with CheastAura and ChestStealer.

WARNING - Putting the radius to above 50 normally highly reduces framerate.

2020-10-25 11:23 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +#include "../../../Utils/Logger.h"
no

2020-10-25 11:26 UTC, richardletshacks requested changes

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +#include "../../../Utils/Logger.h"
no

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +#include "../../DrawUtils.h"
this include is not needed

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +std::vector<vec3_ti> lastPos;
this isnt used anywhere

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +	lastPos.clear();
why?

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +				vec3_t pos = vec3_t(x, y, z);
um?

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.cpp
> +					if (block->toLegacy()->blockId == 54) {
not efficient

2020-10-25 11:26 UTC, richardletshacks commented on Horion/Module/Modules/ChestTP.h
> +	std::vector<vec3_ti> chestlist;
we already have a list of chest blocks

2020-10-25 12:02 UTC, TheArmagan commented on Horion/Module/Modules/ChestTP.cpp
> +				vec3_t pos = vec3_t(x, y, z);
worse than yandere dev

2020-10-28 23:30 UTC, lukizel commented
yanderedev would be proud

2021-01-04 13:29 UTC, N0tExisting commented on Horion/Module/Modules/ChestTP.cpp
> +				vec3_t pos = vec3_t(x, y, z);
[CrystalAura](https://github.com/horionclient/Horion/blob/master/Horion/Module/Modules/CrystalAura.cpp) cough cough

2021-02-11 21:38 UTC, closed without merging