Added Tornado and Player Hitbox Resizer
horionclient/Horion pull request #4371
Opened 2021-01-22 18:49 UTC by grajkogj

dont merge testmodule, I was just using that to test the player resizer before I made a module for it.

2021-01-22 20:54 UTC, Drakesdrs commented
Pretty good alright

2021-01-22 21:15 UTC, Drakesdrs commented
![image](https://user-images.githubusercontent.com/67423571/105547900-eb0add00-5cf6-11eb-911b-957f616e1c7d.png)
Thanks

2021-01-24 19:58 UTC, UltimateBoi commented
lol

2021-01-25 11:47 UTC, N0tExisting requested changes
I'm gona leave my feedback on Hitbox here as it is quite messy
1. You should be able to change hitbox width and height independently of each other
2. Dont override `IModule::onEnable()` and `IModule::onDisable()` they handle all of the enabling & disabling stuff for you
3. use the player's AABB (that's the hitbox)

2021-01-25 11:47 UTC, N0tExisting commented on Horion/Module/Modules/Tornado.cpp
> +	bool onlyJump = this->onlyjump;
You can just check for `this->onlyjump` directly in the if statements

2021-01-25 11:47 UTC, N0tExisting commented on Horion/Module/Modules/Tornado.cpp
> +	} else if (!onlyJump) {
If jump isn't true i has to be false, so you don't need `else if(!onlyJump)`, you can just use `else` instead.

2021-01-25 11:47 UTC, N0tExisting commented on Horion/Module/Modules/HitboxSize.cpp
> +	if (this->active) {
Unless `IMdoule::callWhenDisabled()` returns true the method won't be called when `this->active == false`

2021-01-25 11:47 UTC, N0tExisting commented on Horion/Module/Modules/Tornado.cpp
> +		player->setDamageNearbyMobs(true);
this should be reset in `Tornado::onDisable()` (don't override)

2021-01-25 11:49 UTC, N0tExisting commented on Horion/Module/Modules/HitboxSize1.h
> +	bool active = false;
IModule has something like that

2021-01-25 16:36 UTC, grajkogj commented
@N0tExisting Thanks got the great feedback. I'm new at this and still learning of all the things you can do with horions game modifying properties.

2021-01-25 16:41 UTC, grajkogj commented on Horion/Module/Modules/HitboxSize.cpp
> +	if (this->active) {
I originally didn't have the active variable, but every time I broke a block with it injected, the game would crash. I then made that variable and put the code in an if else statement and that seemed to fix the crash, so I don't really know what that was about.

2021-01-26 09:22 UTC, Cupears commented
I want to get into C++ to contribute to this client, really want to figure out a way to fix .enchant on servers. Time to learn.

2021-01-26 11:43 UTC, ProfessorSlimez commented
> I want to get into C++ to contribute to this client, really want to figure out a way to fix .enchant on servers. Time to learn.

Same but some1 told me it would take a year to learn idk how true that is but yeah be prepared I guess

2021-01-27 12:21 UTC, N0tExisting commented
> > I want to get into C++ to contribute to this client, really want to figure out a way to fix .enchant on servers. Time to learn.
> 
> Same but some1 told me it would take a year to learn idk how true that is but yeah be prepared I guess

If you have some decent experience with other programming languages it might not take that long

2021-01-27 18:12 UTC, probablybased commented
Add the files to CMake

2021-01-28 02:36 UTC, closed without merging