Update CBlockLegacy.h
horionclient/Horion pull request #4426
Opened 2021-08-16 23:53 UTC by FloppyDolphin57

onic86 hac

2021-08-17 15:39 UTC, Intoprelised commented
There is a way you can use enchant how it is but this will help

2021-08-17 20:25 UTC, GodGamer029 requested changes
Good changes, just a few formatting problems here and there

2021-08-17 20:25 UTC, GodGamer029 commented on Horion/DrawUtils.cpp
> +		auto nametagsMod = moduleMgr->getModule<NameTags>();
should be static

2021-08-17 20:25 UTC, GodGamer029 commented on Horion/Module/Modules/Xray.cpp
> +	onEnable();  // yes lol
dude what

2021-08-17 20:25 UTC, GodGamer029 commented on Memory/Hooks.cpp
> +        {
while you're at it, fix this formatting

2021-08-17 20:25 UTC, GodGamer029 commented on Memory/Hooks.cpp
> +        g_Hooks.GetGammaHook = std::make_unique<FuncHook>(fullbright, Hooks::GetGamma);
formatting

2021-08-17 21:33 UTC, Thekingpenguins commented
close da pr is sexy pr

2021-08-18 17:47 UTC, merged

2021-08-18 18:13 UTC, Synx173 commented
epic