better lowhop and fullbright
horionclient/Horion pull request #4428
Opened 2021-08-17 22:08 UTC by Turkeii

2021-08-17 22:10 UTC, Thekingpenguins commented
fuck you turakan lmfao

2021-08-17 22:11 UTC, Intoprelised commented
turkey yummy 🤗

2021-08-17 22:13 UTC, Turkeii commented
> 
> 
> fuck you turakan lmfao

fan

2021-08-17 23:19 UTC, richardletshacks requested changes
the speed thing is just so messed up I don't wanna continue the review anymore, I suggest making seperate pull requests and completely rewriting the speed

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.cpp
> +	this->registerBoolSetting("Boost", &this->Boost, this->Boost);
just check for boost = 0

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.h
> +	SettingEnum Bhopmode;
not following naming conventions

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.h
> +	float Boostnum = 0.10f;
not following naming conventions here either

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.cpp
> +				   .addEntry(EnumEntry("LowhopV2", 0))
name it something else, no idea what the difference between lowhop and lowhopv2 is

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.cpp
> +	switch (Bhopmode.selected) {
wtf?

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.cpp
> +	if (player->isInLava() == 1 || player->isInWater() == 1)
== 1 is redundant

2021-08-17 23:19 UTC, richardletshacks commented on Horion/Module/Modules/Bhop.cpp
> +		dohop = false;
just do ``dohop = pressed && player->onGround``

2021-08-19 21:01 UTC, richardletshacks commented
closed for now, feel free to make a new pull request when the requested changes have been made

2021-08-19 21:01 UTC, closed without merging