Upgraded Horion to VS 2022 and changed some modules to onLevelRender which makes them better and faster
horionclient/Horion pull request #4536
Opened 2021-10-10 22:19 UTC by Intoprelised

onLevelRender is better and faster

2021-10-10 22:28 UTC, Intoprelised commented
what is the error

2021-10-10 22:29 UTC, Intoprelised commented
ohhh the upgrading

2021-10-11 16:38 UTC, N0tExisting commented
> ohhh the upgrading

Update the Workflow I guess

2021-10-12 18:59 UTC, Intoprelised commented
> > ohhh the upgrading
> 
> Update the Workflow I guess

yeah

2021-10-12 19:13 UTC, riesters commented
Horion is dead, no one is going to accept your pull request.

2021-10-12 21:00 UTC, Intoprelised commented
> Horion is dead, no one is going to accept your pull request.

😎😳

2021-10-27 06:50 UTC, N0tExisting requested changes
Idk, why you are using `onLeveRender` instead of `onTick`, you really shouldn't, it might break stuff horribly.

You also need to change the build workflow

2021-10-27 06:50 UTC, N0tExisting commented on Horion/Module/Modules/CrystalAura.cpp
> -void CrystalAura::onTick(C_GameMode* gm) {
No, you might place more than one crystal at once

2021-10-29 00:35 UTC, Intoprelised commented on Horion/Module/Modules/CrystalAura.cpp
> -void CrystalAura::onTick(C_GameMode* gm) {
Thansk for the feedback il re make this a different time and better

2021-10-29 00:35 UTC, closed without merging