made .enchant easier to use
horionclient/Horion pull request #54
Opened 2019-08-27 23:48 UTC by hYdos

i made it so .enchant performs all the steps for nopacket so people dont keep asking questions on HoW DoEs ThIs WoRk

2019-08-28 01:31 UTC, SurvirvorHRG commented on Memory/Hooks.cpp
> +
ghetto code

2019-08-28 01:37 UTC, SurvirvorHRG commented on Horion/Command/Commands/EnchantCommand.cpp
> +	Hooks::ToggleAutoNoPacket();
use moduleMgr->getModule<NoPacket>()->setEnabled(true) instead of that

2019-08-28 01:41 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +	Hooks::ToggleAutoNoPacket();
Sure as soon as I get on my laptop I’ll add that

2019-08-28 03:41 UTC, hYdos commented
any more requests before i run out of data?

2019-08-28 05:09 UTC, ghost requested changes

2019-08-28 05:09 UTC, Godsoft029 commented on Memory/Hooks.h
> +	static void ToggleAutoNoPacket();
remove pls

2019-08-28 05:09 UTC, Godsoft029 commented on Horion/Command/Commands/EnchantCommand.cpp
> +#include "../../../Memory/Hooks.h"
remove pls

2019-08-28 05:09 UTC, Godsoft029 commented on Horion/Command/Commands/EnchantCommand.cpp
> +		moduleMgr->getModuleByName("noPacket")->setEnabled(true);
Use getModule<>()

2019-08-28 05:09 UTC, Godsoft029 commented on Horion/Command/Commands/EnchantCommand.cpp
> +		moduleMgr->getModuleByName("noPacket")->setEnabled(true);
Use getModule<>()

2019-08-28 05:14 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +		moduleMgr->getModuleByName("noPacket")->setEnabled(true);
ok il do those In 7 mins max

2019-08-28 05:20 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +#include "../../../Memory/Hooks.h"
done

2019-08-28 05:20 UTC, hYdos commented on Memory/Hooks.h
> +	static void ToggleAutoNoPacket();
also done

2019-08-28 05:31 UTC, hYdos commented
hmm it still says changes requested after they are all resolved. weird

2019-08-28 05:47 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +		moduleMgr->getModuleByName("noPacket")->setEnabled(true);
done

2019-08-28 09:50 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +		moduleMgr->getModuleByName("noPacket")->setEnabled(true);
done

2019-08-28 09:53 UTC, hYdos commented on Memory/Hooks.h
> +	static void ToggleAutoNoPacket();
done

2019-08-28 20:37 UTC, hYdos commented
added auto .give for people who cant follow steps and just to make it faster

2019-08-28 20:56 UTC, SurvirvorHRG commented on Horion/Command/Commands/GiveCommand.cpp
> +	g_Data.getLocalPlayer()->setOffhandSlot(yot);
lol better to delete .give

2019-08-28 20:57 UTC, hYdos commented on Horion/Command/Commands/GiveCommand.cpp
> +	g_Data.getLocalPlayer()->setOffhandSlot(yot);
wdym like use .setoffhand?

2019-08-28 20:58 UTC, SurvirvorHRG commented on Horion/Command/Commands/EnchantCommand.cpp
> +	moduleMgr->getModule<NoPacket>()->setEnabled(false);
u don't need to enable nopacket just use setoffhand i think it will work

2019-08-28 20:58 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +	moduleMgr->getModule<NoPacket>()->setEnabled(false);
ok ill try that

2019-08-28 21:04 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +	moduleMgr->getModule<NoPacket>()->setEnabled(false);
should i delete setoffhand?

2019-08-28 21:06 UTC, SurvirvorHRG commented on Horion/Command/Commands/EnchantCommand.cpp
> +	moduleMgr->getModule<NoPacket>()->setEnabled(false);
no

2019-08-28 21:06 UTC, hYdos commented on Horion/Command/Commands/EnchantCommand.cpp
> +	moduleMgr->getModule<NoPacket>()->setEnabled(false);
ok

2019-08-28 21:08 UTC, SurvirvorHRG commented on Horion/Command/Commands/GiveCommand.cpp
> +	g_Data.getLocalPlayer()->setOffhandSlot(yot);
now .give and .soh are the same things so it doens't make sense to have two commands that does the same things

2019-08-28 21:13 UTC, hYdos commented on Horion/Command/Commands/GiveCommand.cpp
> +	g_Data.getLocalPlayer()->setOffhandSlot(yot);
removed .give because .setoffhand works better

2019-08-28 21:17 UTC, hYdos commented on Horion/Command/Commands/GiveCommand.cpp
> +	g_Data.getLocalPlayer()->setOffhandSlot(yot);
should i make .give alias of .setoffhand?

2019-08-29 00:14 UTC, hYdos commented
any more requests?

2019-08-29 06:18 UTC, hYdos commented
wasnt getting pulled and got other ideas

2019-08-29 06:18 UTC, closed without merging